CREATE TABLE IF NOT EXISTS concepts (id TEXT PRIMARY KEY, title TEXT NOT NULL, note_text TEXT NOT NULL, mode_pref TEXT NOT NULL DEFAULT 'both', fsrs_card_json TEXT NOT NULL, due INTEGER NOT NULL, last_review INTEGER, state INTEGER NOT NULL, stability REAL NOT NULL, difficulty REAL NOT NULL, next_angle_hint TEXT, created_at INTEGER NOT NULL, archived INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS concept_due ON concepts(due);
CREATE TABLE IF NOT EXISTS concept_edges (id TEXT PRIMARY KEY, from_id TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE, to_id TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE, relation TEXT NOT NULL, status TEXT NOT NULL, rationale TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS edge_unique ON concept_edges(from_id,to_id,relation);
CREATE TABLE IF NOT EXISTS variants (id TEXT PRIMARY KEY, concept_id TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE, type TEXT NOT NULL, bloom_level TEXT NOT NULL, difficulty INTEGER NOT NULL, question_md TEXT NOT NULL, choices TEXT, answer_type TEXT NOT NULL, correct_answer TEXT NOT NULL, accepted_answers TEXT NOT NULL, solution_steps_md TEXT NOT NULL, rubric TEXT NOT NULL, hint TEXT, anchor_quote TEXT NOT NULL, status TEXT NOT NULL, verification_report TEXT NOT NULL, times_shown INTEGER NOT NULL DEFAULT 0, report_count INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS variant_pool ON variants(concept_id,status);
CREATE TABLE IF NOT EXISTS reviews (id TEXT PRIMARY KEY, concept_id TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE, variant_id TEXT REFERENCES variants(id) ON DELETE SET NULL, user_answer TEXT NOT NULL, self_rating INTEGER, verdict TEXT NOT NULL, rating INTEGER NOT NULL, grader_reasoning TEXT NOT NULL, response_time_ms INTEGER NOT NULL, hint_used INTEGER NOT NULL, user_override_verdict TEXT, error_summary TEXT, selection_reason TEXT NOT NULL, card_state_before_json TEXT NOT NULL, card_state_after_json TEXT NOT NULL, reviewed_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS review_concept ON reviews(concept_id,reviewed_at);
CREATE TABLE IF NOT EXISTS llm_calls (id TEXT PRIMARY KEY, purpose TEXT NOT NULL, model TEXT NOT NULL, input_tokens INTEGER NOT NULL, output_tokens INTEGER NOT NULL, latency_ms INTEGER NOT NULL, created_at INTEGER NOT NULL);
